package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
)

// Only the Traefik adapter can assert this relationship: same router and path,
// with each address declared by that router. Ordinary identity conflicts still fail.
func mergeAliasApps(tx *sql.Tx, ids []string, source string) error {
	canonical := ids[0]
	merged := override{}
	explicit := map[string]bool{}
	for _, id := range ids {
		rows, err := tx.Query("SELECT key FROM identities WHERE app_id=? AND key LIKE 'explicit:%'", id)
		if err != nil {
			return err
		}
		for rows.Next() {
			var key string
			if err = rows.Scan(&key); err != nil {
				rows.Close()
				return err
			}
			explicit[key] = true
		}
		err = rows.Err()
		rows.Close()
		if err != nil {
			return err
		}
		if len(explicit) > 1 {
			return fmt.Errorf("alias group %s has conflicting explicit Apptrail IDs; previous records were retained", source)
		}
		var raw string
		if err = tx.QueryRow("SELECT overrides FROM applications WHERE id=?", id).Scan(&raw); err != nil {
			return err
		}
		var ov override
		if err = json.Unmarshal([]byte(raw), &ov); err != nil {
			return err
		}
		fields := []struct {
			name   string
			target **string
			value  *string
		}{
			{"name", &merged.Name, ov.Name}, {"description", &merged.Description, ov.Description}, {"url", &merged.URL, ov.URL}, {"icon", &merged.Icon, ov.Icon}, {"category", &merged.Category, ov.Category},
		}
		for _, field := range fields {
			if field.value == nil {
				continue
			}
			if *field.target != nil && **field.target != *field.value {
				return fmt.Errorf("alias group %s has conflicting %s overrides; align them before rescanning. Previous records were retained", source, field.name)
			}
			*field.target = field.value
		}
		for _, field := range []struct {
			target **bool
			value  *bool
		}{{&merged.Favorite, ov.Favorite}, {&merged.Hidden, ov.Hidden}} {
			if field.value == nil {
				continue
			}
			value := *field.value
			if *field.target != nil {
				value = value || **field.target
			}
			*field.target = &value
		}
	}
	rows, err := tx.Query("SELECT id,items FROM dashboards")
	if err != nil {
		return err
	}
	updates := map[string]string{}
	for rows.Next() {
		var id, raw string
		if err = rows.Scan(&id, &raw); err != nil {
			rows.Close()
			return err
		}
		var items []string
		if err = json.Unmarshal([]byte(raw), &items); err != nil {
			rows.Close()
			return err
		}
		result := []string{}
		changed := false
		for _, item := range items {
			if contains(ids, item) {
				if item != canonical {
					changed = true
				}
				item = canonical
				if contains(result, item) {
					changed = true
					continue
				}
			}
			result = append(result, item)
		}
		if changed {
			updates[id] = encode(result)
		}
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		return err
	}
	for id, items := range updates {
		if _, err = tx.Exec("UPDATE dashboards SET items=? WHERE id=?", items, id); err != nil {
			return err
		}
	}
	if _, err = tx.Exec("UPDATE applications SET overrides=? WHERE id=?", encode(merged), canonical); err != nil {
		return err
	}
	for _, id := range ids[1:] {
		if _, err = tx.Exec("UPDATE identities SET app_id=? WHERE app_id=?", canonical, id); err != nil {
			return err
		}
		if _, err = tx.Exec("UPDATE observations SET app_id=? WHERE app_id=? AND provider!='http'", canonical, id); err != nil {
			return err
		}
		// HTTP metadata for discarded IDs is derived and will be refreshed for the surviving app.
		if _, err = tx.Exec("DELETE FROM applications WHERE id=?", id); err != nil {
			return err
		}
	}
	return nil
}

func pruneTraefikInternals(tx *sql.Tx, provider string) error {
	// Retire only uncustomized noise generated by older versions. User-edited,
	// placed, or otherwise discovered apps remain available as missing records.
	_, err := tx.Exec(`DELETE FROM applications
WHERE overrides='{}'
AND EXISTS (SELECT 1 FROM observations o WHERE o.app_id=applications.id AND o.provider=? AND o.present=0 AND json_extract(o.payload,'$.facts.router.value') LIKE '%@internal')
AND NOT EXISTS (SELECT 1 FROM dashboards d,json_each(d.items) item WHERE item.value=applications.id)
AND NOT EXISTS (SELECT 1 FROM identities i WHERE i.app_id=applications.id AND i.key LIKE 'explicit:%')
AND NOT EXISTS (SELECT 1 FROM observations o WHERE o.app_id=applications.id AND o.provider!='http' AND NOT (o.provider=? AND o.present=0 AND COALESCE(json_extract(o.payload,'$.facts.router.value'),'') LIKE '%@internal'))`, provider, provider)
	return err
}
